# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 363)
        self.sortEdit = QtWidgets.QLineEdit(Form)
        self.sortEdit.setGeometry(QtCore.QRect(100, 50, 201, 22))
        self.sortEdit.setObjectName("sortEdit")
        self.hotEdit = QtWidgets.QLineEdit(Form)
        self.hotEdit.setGeometry(QtCore.QRect(100, 100, 201, 22))
        self.hotEdit.setObjectName("hotEdit")
        self.descriptionEdit = QtWidgets.QLineEdit(Form)
        self.descriptionEdit.setGeometry(QtCore.QRect(100, 180, 201, 22))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.priceEdit = QtWidgets.QLineEdit(Form)
        self.priceEdit.setGeometry(QtCore.QRect(100, 220, 201, 22))
        self.priceEdit.setObjectName("priceEdit")
        self.volumeEdit = QtWidgets.QLineEdit(Form)
        self.volumeEdit.setGeometry(QtCore.QRect(100, 260, 201, 22))
        self.volumeEdit.setObjectName("volumeEdit")
        self.typeEdit = QtWidgets.QLineEdit(Form)
        self.typeEdit.setGeometry(QtCore.QRect(100, 140, 201, 22))
        self.typeEdit.setObjectName("typeEdit")
        self.submitButton = QtWidgets.QPushButton(Form)
        self.submitButton.setGeometry(QtCore.QRect(150, 310, 93, 28))
        self.submitButton.setObjectName("submitButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sortEdit.setPlaceholderText(_translate("Form", "Введите сорт"))
        self.hotEdit.setPlaceholderText(_translate("Form", "Введите степень прожарки"))
        self.descriptionEdit.setPlaceholderText(_translate("Form", "Введите описание"))
        self.priceEdit.setPlaceholderText(_translate("Form", "Введите цену"))
        self.volumeEdit.setPlaceholderText(_translate("Form", "Введите объем"))
        self.typeEdit.setPlaceholderText(_translate("Form", "Введите тип"))
        self.submitButton.setText(_translate("Form", "Добавить"))
